# Generated by Django 4.1.7 on 2023-04-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.TextField()),
                ('phone', models.IntegerField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('department', models.TextField()),
                ('material', models.TextField()),
            ],
        ),
    ]
