# Generated by Django 4.1.7 on 2023-04-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='Gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='department',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='material',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='name',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
